"""
core.py — the actual scanning and deleting logic.

Kept completely separate from the UI so it can be tested on its own
and so the dangerous part (deleting files) lives in one auditable place.

Safety rules baked in here, not in the UI:
  - we only ever look at / delete things INSIDE a `.godot/` directory
  - a folder only counts as a Godot project if it has `project.godot`
  - we never touch `project.godot`, source files, or anything outside `.godot/`
  - delete is a separate explicit call from scan; scanning never mutates
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass, field
from pathlib import Path

# Subfolders / files inside .godot that are safe to remove. These are all
# regenerated by the editor on next open. This is an allowlist on purpose —
# anything not named here is left alone, even if it's inside .godot.
SAFE_CACHE_NAMES = {
    "imported",        # imported asset cache (the big one)
    "shader_cache",    # compiled shader cache
    "editor",          # editor layout/state cache (regenerated)
    ".gdignore",       # harmless, but sometimes left dangling
}

# Names we refuse to delete no matter what. Belt and suspenders.
NEVER_DELETE = {
    "project.godot",
    "global_script_class_cache.cfg",  # mildly annoying to lose, keep it
}


@dataclass
class CacheItem:
    """One deletable thing found inside a project's .godot/ folder."""
    path: Path
    size_bytes: int
    is_dir: bool

    @property
    def human_size(self) -> str:
        return human_bytes(self.size_bytes)


@dataclass
class ProjectScan:
    """Result of scanning a single Godot project."""
    project_root: Path
    godot_dir: Path
    items: list[CacheItem] = field(default_factory=list)

    @property
    def total_bytes(self) -> int:
        return sum(i.size_bytes for i in self.items)

    @property
    def human_total(self) -> str:
        return human_bytes(self.total_bytes)


def human_bytes(n: int) -> str:
    """1536 -> '1.5 KB'. Keeps it readable in the table."""
    step = 1024.0
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if n < step:
            return f"{n:.0f} {unit}" if unit == "B" else f"{n:.1f} {unit}"
        n /= step
    return f"{n:.1f} PB"


def is_godot_project(folder: Path) -> bool:
    """A folder is a project only if project.godot sits directly in it."""
    return (folder / "project.godot").is_file()


def _dir_size(path: Path) -> int:
    """Sum of file sizes under path. Skips symlinks so we never follow one
    out of the .godot sandbox."""
    total = 0
    for p in path.rglob("*"):
        try:
            if p.is_symlink():
                continue
            if p.is_file():
                total += p.stat().st_size
        except OSError:
            # file vanished mid-scan or perms — just skip it
            continue
    return total


def find_projects(search_root: Path) -> list[Path]:
    """Walk search_root and return every folder containing project.godot.

    Stops descending into a project's own subfolders for speed — a Godot
    project doesn't normally nest another project inside it.
    """
    search_root = search_root.expanduser().resolve()
    found: list[Path] = []
    if is_godot_project(search_root):
        found.append(search_root)
        return found

    for project_file in search_root.rglob("project.godot"):
        try:
            if project_file.is_file():
                found.append(project_file.parent)
        except OSError:
            continue
    return found


def scan_project(project_root: Path) -> ProjectScan:
    """Look inside one project's .godot/ and list the safe-to-delete cache.

    Pure read-only. Returns a ProjectScan; deletes nothing.
    """
    project_root = project_root.expanduser().resolve()
    godot_dir = project_root / ".godot"
    scan = ProjectScan(project_root=project_root, godot_dir=godot_dir)

    if not is_godot_project(project_root):
        return scan  # not a real project, return empty
    if not godot_dir.is_dir():
        return scan  # no cache yet, nothing to do

    for child in godot_dir.iterdir():
        if child.name in NEVER_DELETE:
            continue
        if child.name not in SAFE_CACHE_NAMES:
            continue  # allowlist: skip anything we don't explicitly trust
        try:
            if child.is_symlink():
                continue  # never delete through a symlink
            if child.is_dir():
                size = _dir_size(child)
                scan.items.append(CacheItem(child, size, is_dir=True))
            elif child.is_file():
                size = child.stat().st_size
                scan.items.append(CacheItem(child, size, is_dir=False))
        except OSError:
            continue

    return scan


def _is_safe_to_delete(item_path: Path, godot_dir: Path) -> bool:
    """Final gate before any rm. Confirms the resolved path really does
    live inside the resolved .godot dir and matches the allowlist.

    This is the function that stops a bug elsewhere from deleting your repo.
    """
    try:
        item_resolved = item_path.resolve()
        godot_resolved = godot_dir.resolve()
    except OSError:
        return False

    # must be strictly inside .godot/
    if godot_resolved not in item_resolved.parents:
        return False
    # name must be on the allowlist and not on the never-list
    if item_resolved.name in NEVER_DELETE:
        return False
    if item_resolved.name not in SAFE_CACHE_NAMES:
        return False
    return True


@dataclass
class DeleteResult:
    deleted: list[Path] = field(default_factory=list)
    freed_bytes: int = 0
    errors: list[tuple[Path, str]] = field(default_factory=list)

    @property
    def human_freed(self) -> str:
        return human_bytes(self.freed_bytes)


def delete_items(scan: ProjectScan, items: list[CacheItem]) -> DeleteResult:
    """Delete the chosen items. Each one re-checked against the safety gate
    immediately before removal — the UI's selection is not trusted blindly.
    """
    result = DeleteResult()
    for item in items:
        if not _is_safe_to_delete(item.path, scan.godot_dir):
            result.errors.append((item.path, "failed safety check, skipped"))
            continue
        try:
            if item.is_dir:
                shutil.rmtree(item.path)
            else:
                item.path.unlink()
            result.deleted.append(item.path)
            result.freed_bytes += item.size_bytes
        except OSError as e:
            result.errors.append((item.path, str(e)))
    return result
